// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/employee-dash/Atual.tsx": () => import("../components/mockups/employee-dash/Atual.tsx"),
  "./components/mockups/employee-dash/Minimalista.tsx": () => import("../components/mockups/employee-dash/Minimalista.tsx"),
  "./components/mockups/employee-dash/Moderno.tsx": () => import("../components/mockups/employee-dash/Moderno.tsx")
};
